package dev.zm.itemsbuilder.migration;

import dev.zm.itemsbuilder.zMItemsBuilder;
import dev.zm.itemsbuilder.config.LanguageManager;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;

public final class MigrationManager {

    private static final int BUNDLED_CONFIG_VERSION = 3;
    private static final int BUNDLED_LANG_VERSION = 6;

    private final zMItemsBuilder plugin;
    private final LanguageManager languageManager;

    public MigrationManager(zMItemsBuilder plugin, LanguageManager languageManager) {
        this.plugin = plugin;
        this.languageManager = languageManager;
    }

    public boolean performMigrations() {
        boolean anyMigrated = false;

        if (migrateConfig()) {
            anyMigrated = true;
        }

        if (migrateLanguageFiles()) {
            anyMigrated = true;
        }

        if (ensureDataFiles()) {
            anyMigrated = true;
        }

        if (anyMigrated) {
            plugin.reloadConfig();
            languageManager.reload();
            plugin.getLogger().info("All configurations reloaded after migration.");
        }

        return anyMigrated;
    }

    private boolean ensureDataFiles() {
        boolean createdAny = false;
        String[] files = { "items.yml", "data.yml" };
        for (String fileName : files) {
            File file = new File(plugin.getDataFolder(), fileName);
            if (!file.exists()) {
                if (copyResourceToFile(fileName, file)) {
                    plugin.getLogger().info("Created default " + fileName + " from bundled resource.");
                    createdAny = true;
                } else {
                    try {
                        file.createNewFile();
                        Files.write(file.toPath(), ("# " + fileName + " generated by zMItemsBuilder\n").getBytes());
                        plugin.getLogger().info("Created empty " + fileName + " (no bundled resource found).");
                        createdAny = true;
                    } catch (IOException e) {
                        plugin.getLogger().log(Level.WARNING, "Could not create " + fileName, e);
                    }
                }
            }
        }
        return createdAny;
    }

    private boolean migrateConfig() {
        File configFile = new File(plugin.getDataFolder(), "config.yml");
        if (!configFile.exists()) {
            return false;
        }

        FileConfiguration config = YamlConfiguration.loadConfiguration(configFile);
        int currentVersion = config.getInt("config-version", 1);

        if (currentVersion >= BUNDLED_CONFIG_VERSION) {
            return false;
        }

        createBackup(configFile);

        if (!copyResourceToFile("config.yml", configFile)) {
            plugin.getLogger().severe("Failed to overwrite config.yml with bundled version.");
            return false;
        }

        plugin.getLogger()
                .info("config.yml was overwritten with the new bundled version (was v" + currentVersion + ").");
        return true;
    }

    private boolean migrateLanguageFiles() {
        File langFolder = new File(plugin.getDataFolder(), "lang");
        if (!langFolder.exists() || !langFolder.isDirectory()) {
            return false;
        }

        boolean anyMigrated = false;
        File[] files = langFolder.listFiles((dir, name) -> name.toLowerCase(Locale.ROOT).startsWith("lang_")
                && name.toLowerCase(Locale.ROOT).endsWith(".yml"));

        if (files == null) {
            return false;
        }

        for (File file : files) {
            if (migrateLanguageFile(file)) {
                anyMigrated = true;
            }
        }
        return anyMigrated;
    }

    private boolean migrateLanguageFile(File file) {
        FileConfiguration langConfig = YamlConfiguration.loadConfiguration(file);
        int currentVersion = langConfig.getInt("version", 0);

        if (currentVersion >= BUNDLED_LANG_VERSION) {
            return false;
        }

        String fileName = file.getName();
        String langCode = fileName.substring(5, fileName.length() - 4);

        createBackup(file);

        String resourcePath = "lang/" + fileName;
        if (copyResourceToFile(resourcePath, file)) {
            plugin.getLogger().info("Language file " + fileName + " was overwritten with bundled version (was v"
                    + currentVersion + ").");
            return true;
        } else {
            plugin.getLogger().warning("Bundled version of " + fileName + " not found. Only updating version number.");
            langConfig.set("version", BUNDLED_LANG_VERSION);
            try {
                langConfig.save(file);
                plugin.getLogger()
                        .info("Language file " + fileName + " version updated to " + BUNDLED_LANG_VERSION + ".");
                return true;
            } catch (IOException e) {
                plugin.getLogger().log(Level.SEVERE, "Failed to save updated version for " + fileName, e);
                return false;
            }
        }
    }

    private boolean copyResourceToFile(String resourcePath, File destination) {
        try (InputStream is = plugin.getResource(resourcePath)) {
            if (is == null) {
                plugin.getLogger().warning("Resource not found in JAR: " + resourcePath);
                return false;
            }
            File parent = destination.getParentFile();
            if (parent != null && !parent.exists()) {
                parent.mkdirs();
            }
            Files.copy(is, destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
            return true;
        } catch (IOException e) {
            plugin.getLogger().log(Level.SEVERE,
                    "Failed to copy resource " + resourcePath + " to " + destination.getPath(), e);
            return false;
        }
    }

    private void createBackup(File file) {
        File backupFolder = new File(plugin.getDataFolder(), "backups");
        if (!backupFolder.exists()) {
            backupFolder.mkdirs();
        }
        String timestamp = new SimpleDateFormat("yyyy-MM-dd_HH-mm-ss").format(new Date());
        String backupName = file.getName() + "_" + timestamp + ".backup";
        File backupFile = new File(backupFolder, backupName);
        try {
            Files.copy(file.toPath(), backupFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            plugin.getLogger().info("Backup created: " + backupFile.getName());
        } catch (IOException e) {
            plugin.getLogger().log(Level.WARNING, "Could not create backup for " + file.getName(), e);
        }
    }
}